version: "3.8"

services:
  springapi:
    container_name: springapp
    build: ./
    restart: on-failure
    
    ports:
      - 8081:8080
      
    environment:
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/EventMS